name: Build and Release TA-nix Checker

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    name: Build and Publish Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare build structure
        run: |
          mkdir -p ta-nix-checker/usr/local/bin
          cp scripts/ta_nix_verification_cli.py ta-nix-checker/usr/local/bin/
          echo '#!/bin/bash' > ta-nix-checker/usr/local/bin/ta-nix-check
          echo 'exec python3 /usr/local/bin/ta_nix_verification_cli.py "$@"' >> ta-nix-checker/usr/local/bin/ta-nix-check
          chmod +x ta-nix-checker/usr/local/bin/ta-nix-check

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Create DEBIAN control file
        run: |
          mkdir -p ta-nix-checker/DEBIAN
          echo "Package: ta-nix-checker" > ta-nix-checker/DEBIAN/control
          echo "Version: ${{ env.VERSION }}" >> ta-nix-checker/DEBIAN/control
          echo "Section: utils" >> ta-nix-checker/DEBIAN/control
          echo "Priority: optional" >> ta-nix-checker/DEBIAN/control
          echo "Architecture: all" >> ta-nix-checker/DEBIAN/control
          echo "Maintainer: Levi Lima Greter" >> ta-nix-checker/DEBIAN/control
          echo "Description: Verificador de pré-requisitos para o Splunk Add-on for Unix/Linux (TA-nix)" >> ta-nix-checker/DEBIAN/control

      - name: Build .deb package
        run: |
          dpkg-deb --build ta-nix-checker
          mv ta-nix-checker.deb ta-nix-checker_${{ env.VERSION }}.deb

      - name: Build .tar.gz package
        run: |
          tar -czf ta-nix-checker-${{ env.VERSION }}.tar.gz ta-nix-checker

      - name: Install fpm
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm

      - name: Build .rpm package
        run: |
          mkdir -p rpmroot/usr/local/bin
          cp scripts/ta_nix_verification_cli.py rpmroot/usr/local/bin/
          echo '#!/bin/bash' > rpmroot/usr/local/bin/ta-nix-check
          echo 'exec python3 /usr/local/bin/ta_nix_verification_cli.py "$@"' >> rpmroot/usr/local/bin/ta-nix-check
          chmod +x rpmroot/usr/local/bin/ta-nix-check
          fpm -s dir -t rpm -n ta-nix-checker -v ${{ env.VERSION }} -C rpmroot .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ta-nix-checker_${{ env.VERSION }}.deb
            ta-nix-checker-${{ env.VERSION }}.tar.gz
            ta-nix-checker-${{ env.VERSION }}.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}