name: Build and Release TA-nix Checker

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    name: Build .deb and Publish Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Prepare build structure
        run: |
          mkdir -p ta-nix-checker/usr/local/bin
          cp ta_nix_verification_cli.py ta-nix-checker/usr/local/bin/
          echo '#!/bin/bash' > ta-nix-checker/usr/local/bin/ta-nix-check
          echo 'exec python3 /usr/local/bin/ta_nix_verification_cli.py "$@"' >> ta-nix-checker/usr/local/bin/ta-nix-check
          chmod +x ta-nix-checker/usr/local/bin/ta-nix-check

      - name: Create DEBIAN control file with dynamic version
        run: |
          mkdir -p ta-nix-checker/DEBIAN
          cat <<EOF > ta-nix-checker/DEBIAN/control
Package: ta-nix-checker
Version: ${{ steps.vars.outputs.VERSION }}
Section: utils
Priority: optional
Architecture: all
Maintainer: Levi Lima Greter
Description: Verificador de pré-requisitos para o Splunk Add-on for Unix/Linux (TA-nix)
EOF

      - name: Build .deb package
        run: |
          dpkg-deb --build ta-nix-checker
          mv ta-nix-checker.deb ta-nix-checker_${{ steps.vars.outputs.VERSION }}.deb

      - name: Upload .deb to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ta-nix-checker_${{ steps.vars.outputs.VERSION }}.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}