name: Build and Release TA-nix Checker

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Extrair versão da tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Preparar estrutura do pacote
        run: |
          mkdir -p ta-nix-checker/usr/local/bin
          cp scripts/ta_nix_verification_cli.py ta-nix-checker/usr/local/bin/
          echo '#!/bin/bash' > ta-nix-checker/usr/local/bin/ta-nix-check
          echo 'exec python3 /usr/local/bin/ta_nix_verification_cli.py "$@"' >> ta-nix-checker/usr/local/bin/ta-nix-check
          chmod +x ta-nix-checker/usr/local/bin/ta-nix-check

      - name: Criar pacote .deb
        run: |
          mkdir -p ta-nix-checker/DEBIAN
          cat <<EOF > ta-nix-checker/DEBIAN/control
Package: ta-nix-checker
Version: ${{ env.VERSION }}
Section: utils
Priority: optional
Architecture: all
Maintainer: Levi Lima Greter
Description: Verificador de pré-requisitos para o Splunk Add-on for Unix/Linux (TA-nix)
EOF
          dpkg-deb --build ta-nix-checker
          mv ta-nix-checker.deb ta-nix-checker_${{ env.VERSION }}.deb

      - name: Criar pacote .tar.gz
        run: |
          tar -czf ta-nix-checker-${{ env.VERSION }}.tar.gz -C ta-nix-checker .

      - name: Criar pacote .rpm (via fpm)
        run: |
          sudo apt-get update && sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm
          fpm -s dir -t rpm -n ta-nix-checker -v ${{ env.VERSION }} -C ta-nix-checker .

      - name: Renomear .rpm corretamente
        run: |
          mv ta-nix-checker-${{ env.VERSION }}-1.noarch.rpm ta-nix-checker-${{ env.VERSION }}.rpm

      - name: Publicar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ta-nix-checker_${{ env.VERSION }}.deb
            ta-nix-checker-${{ env.VERSION }}.tar.gz
            ta-nix-checker-${{ env.VERSION }}.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}